### ISSUE TITLE
biggest issue here is 

### ISSUE THREAD

**Issue by rainreach** [ImSeaWorld/LMAOnline-Server#1]
you aint even put the Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'MySql' could not be found (are you missing a using directive or an assembly reference?)	GSN	C:\Users\izaih\Desktop\LMAOnline-Server-95840fcac8bda2bef3018ed8659c15c96693fef4\LMAOnline-Server-95840fcac8bda2bef3018ed8659c15c96693fef4\Servers C#\LMAOnline v4\Generic Server Name (v4.2)\Globals\Global Functions.cs	19	N/A
its not found you uploaded a broken server thats why

**Comment by ImSeaWorld** [comment]
Was never meant to be released. There's also multiple versions of it, I put it up on github for preservation. As I state "4.2 is not finished". So the "broken server" is not broken, because it was never finished. Go get spoon fed elsewhere because I'm not going to hold your hand on a project that's more than 3 years old...
